name: Build App Manager

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: 17
          distribution: temurin
      
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y gradle texlive pandoc
      
    - name: Install bundletool on Linux
      run: |
        wget 'https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar'
        mv bundletool-all-1.15.6.jar bundletool-all.jar
    - name: Configure bundletool on path
      run: |
        echo "java -jar bundletool-all.jar" > bundletool
        chmod +x bundletool
        mv bundletool /usr/bin

    # - name: Clone repository with submodules
    #   run: git clone --recurse-submodules https://github.com/MuntashirAkon/AppManager.git
      
    # - name: Build debug version of App Manager
    #   run: |
    #     cd AppManager
    #     ./gradlew packageDebugUniversalApk
      
    - name: Create Bundled App (APKS format)
      run: |
        chmod +x ./scripts/aab_to_apks.sh
        ./scripts/aab_to_apks.sh debug
